### ISSUE TITLE
Docs: SVG elements missing in docs

### ISSUE THREAD

**Issue by kanthgithub** [frak-id/wallet#9]
- SVG elements missing in docs which is causing error while rendering the sequence diagram script to diagram
![image](https://github.com/frak-id/wallet/assets/9845122/7f56fbcb-2de1-4b2e-aec5-5ba7e744a63f)
![image](https://github.com/frak-id/wallet/assets/9845122/96129e7a-c80e-4aba-9d02-ccacf39442ae)
![image](https://github.com/frak-id/wallet/assets/9845122/d8e5472c-0204-4e7c-bccb-ed58d44f87c8)
![image](https://github.com/frak-id/wallet/assets/9845122/9632e2ef-5c57-4689-951e-dfb19c9a49e0)

**Comment by KONFeature** [comment]
Nice catch ser 👍 
It's seems to be an issue with github render or smth like that, in the meantime, you can find our graphs here: https://docs.frak.id/wallet-sdk/graphs

**Comment by KONFeature** [comment]
Nice catch ser 👍
It's seems to be an issue with github render or smth like that, in the meantime, you can find our graphs here: https://docs.frak.id/wallet-sdk/graphs
